global  using GetClientAllCommandRequest = ecobony.application.Feauters.Query.Language.GetClientAllCommandRequest;
global using GetClientAllCommandResponse = ecobony.application.Feauters.Query.Language.GetClientAllCommandResponse;
global using DeleteCommandRequest = ecobony.application.Feauters.Command.Language.DeleteCommandRequest;
global using DeleteCommandResponse = ecobony.application.Feauters.Command.Language.DeleteCommandResponse;
global using GetByIdCommandRequest = ecobony.application.Feauters.Query.Language.GetByIdCommandRequest;
global using GetByIdCommandResponse = ecobony.application.Feauters.Query.Language.GetByIdCommandResponse;
global using RestoreCommandRequest = ecobony.application.Feauters.Command.Language.RestoreCommandRequest;
global using RestoreCommandResponse = ecobony.application.Feauters.Command.Language.RestoreCommandResponse;
global using SoftDeleteCommandRequest = ecobony.application.Feauters.Command.Language.SoftDeleteCommandRequest;
global using SoftDeleteCommandResponse = ecobony.application.Feauters.Command.Language.SoftDeleteCommandResponse;

global using ecobony.application.Feauters.Command;
global using ecobony.application.Feauters.Query;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;

global using ecobony.application.Services;
global using Microsoft.AspNetCore.Mvc.Filters;
global using ecobony.application.Repository;
global using ecobony.application.Feauters.Query.Header;
global using ecobony.application.Feauters.Command.Header;
global using ecobony.application.Feauters.Query.Language;
global using Microsoft.AspNetCore.ResponseCompression;
global using Microsoft.Extensions.Caching.Memory;
global using Microsoft.Extensions.Localization;
global using System.IO.Compression;

global using System.Text.Json.Serialization; 
global using System.Collections.Concurrent;
global using ecobony.application.Validator;
global using ecobony.domain.Dto_s;
global using Microsoft.AspNetCore.Localization;
global  using ecobony.infrastructur;
global using ecobony.webapi.Filter;
global using System.Globalization;
global using System.Text.Json;
global using ecobony.application;
global using ecobony.persistence;
global using System.Reflection;
global using FluentValidation;
global using ecobony.signair;
global using System.Net;
global using MediatR;
